run_config:
  name: random-forest-featset-1
  author: Jackie Kim
  version: default
  description: Classifies clouds into one of two types listed in cloud data from UC Irvine.
  dependencies: requirements.txt
  data_source: https://archive.ics.uci.edu/ml/machine-learning-databases/undocumented/taylor/cloud.data
  output: "runs"

create_dataset:
  input_path: "./runs/clouds.data"
  output_path: "./output/"
  columns:
    - visible_mean
    - visible_max
    - visible_min
    - visible_mean_distribution
    - visible_contrast
    - visible_entropy
    - visible_second_angular_momentum
    - IR_mean
    - IR_max
    - IR_min

generate_features:
  calculate_norm_range:
    IR_norm_range:
      min_col: IR_min
      max_col: IR_max
      mean_col: IR_mean
  log_transform:
    log_entropy: visible_entropy
  multiply:
    entropy_x_contrast:
      col_a: visible_contrast
      col_b: visible_entropy

train_model:
  model_type: RandomForestClassifier
  parameters:
    n_estimators: 10
    max_depth: 10
  train_test_split_ratio: 0.4

score_model:
  method: "predict_proba"

evaluate_performance:
  metrics:
    - auc
    - accuracy
    - confusion_matrix
    - classification_report

aws:
  upload: True
  bucket_name: mnk1906-clouds
  prefix: experiments
